### ISSUE TITLE
Error building for i386/Windows

### ISSUE THREAD

**Issue by synopse** [newpascal/fpcupdeluxe#9] opened 2017-03-27 14:25 UTC
When building FPC + Lazarus from NewPascal repositories (I tested both GIT or SVN).
I setup the destination folder to C:\newpascal.
It fails with a GPF when building Lazarus.

From fpcupdeluxe-i386-win32.log file:
` [2017-03-27 15:06:33.125 Info] Execute: C:\newpascal\fpcbootstrap\make.exe. Params: FPC=C:\newpascal\fpc\bin\i386-win32\fpc.exe,USESVN2REVISIONINC=0,--directory=C:\newpascal\lazarus,INSTALL_PREFIX=C:\newpascal\lazarus,FPCDIR=C:\newpascal\fpcsrc,UPXPROG=echo,COPYTREE=echo,"OPT=-vw-n-h-i-l-d-u-t-p-c-x- ",lazbuild`
` [2017-03-27 15:06:33.132 Info] Verbose output saved to Z:\Temp\TMP00005.tmp`
` [2017-03-27 15:07:05.566 Info] Lazarus: lazbuild could not be found, so cannot build USERIDE.`

Associated TMP00005.tmp is attached.

There **is** a lazbuild.exe file in the c:\newpascal\lazarus\ folder.

Seems like there is a c:\fpcupdeluxe folder generated...
I will retry with no customization of the output folder to c:\newpascal

[TMP00005.tmp.txt](https://github.com/newpascal/fpcupdeluxe/files/872695/TMP00005.tmp.txt)
[fpcupdeluxe-i386-win32.log.txt](https://github.com/newpascal/fpcupdeluxe/files/872696/fpcupdeluxe-i386-win32.log.txt)

**Comment by LongDirtyAnimAlf** [comment] 2017-03-28 06:42
Unfortunately, I cannot reproduce this issue.
Therefor, I would like to ask you to re-run, and post a copy of the (green) command-screen log (right-click).
This could give somewhat more detailed info.

**Comment by LongDirtyAnimAlf** [comment] 2017-04-25 14:05
Closing: no feedback.
Feedback would still be welcome however, due to other reports about this error.

**Closed by LongDirtyAnimAlf** 2017-04-25 14:05 UTC
